version: 2.1

orbs:
  release: sharptools/release@0.0.3
  go: sharptools/go@0.0.6


workflows:
  workflow:
    jobs:
      - go/package:
          appname: gopack

      - release/github_job:
          context: General
          requires:
            - go/package
          filters:
            branches:
              only: master
